# .pre-commit-config.yaml
# See https://pre-commit.com for more information

repos:
-   repo: local
    hooks:
    -   id: lint
        name: Run project linters
        entry: make lint
        language: system
        pass_filenames: false
        always_run: true 