version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - ENVIRONMENT=production
    # Volumes are removed for a production-style build to ensure the image is self-contained
    # volumes:
    #   - ./backend:/app
    #   - backend_venv:/app/.venv
    networks:
      - app-network

# The backend_venv volume is no longer needed as we install into the image
# volumes:
#   backend_venv:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge 