"""feat(db): add patient_id and case_id to complaints table

Revision ID: 4ffc07840df0
Revises: f804fe9b28e4
Create Date: 2025-06-23 10:00:35.221847

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ffc07840df0'
down_revision: Union[str, None] = 'f804fe9b28e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.add_column('complaints', sa.Column('case_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'complaints', 'patients',
                          ['patient_id'], ['patient_id'])
    op.create_foreign_key(None, 'complaints', 'cases', ['case_id'], ['case_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'case_id')
    op.drop_column('complaints', 'patient_id')
    # ### end Alembic commands ###
