"""feat(db): add patients and cases tables

Revision ID: f804fe9b28e4
Revises: beb1e6faf406
Create Date: 2025-06-23 09:54:20.562458

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f804fe9b28e4'
down_revision: Union[str, None] = 'beb1e6faf406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('case_reference', sa.String(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('case_reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    op.drop_table('patients')
    # ### end Alembic commands ###
