name: Deploy Backend to Railway

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Backend to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          
          # Authenticate with Railway
          echo "Logging in to Railway..."
          railway login --token=${{ secrets.RAILWAY_TOKEN }}
          
          # Link to the service
          railway link --service=${{ secrets.RAILWAY_BACKEND_SERVICE_ID }} --project_id=${{ secrets.RAILWAY_PROJECT_ID }}
          
          # Run database migrations first
          echo "Running database migrations..."
          railway run alembic upgrade head
          
          # Deploy the service
          echo "Deploying backend service..."
          railway up --detach

      - name: Verify Deployment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          echo "Deployment completed. Checking service status..."
          railway status 